---
- hosts: k3s_master
  gather_facts: no
  tasks:
    - name: Download kubeconfig
      ansible.builtin.fetch:
        src: "~{{ ansible_user }}/.kube/config"
        dest: "{{ playbook_dir }}/kubeconfig"
        flat: yes
