apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: kube-system
spec:
  chart: longhorn
  repo: https://charts.longhorn.io
  targetNamespace: longhorn-system
  createNamespace: true
  valuesContent: |-
    defaultSettings:
      defaultDataPath: /mnt/storage
      defaultReplicaCount: 2
      storageReservedPercentageForDefaultDisk: 0
    ingress:
      enabled: true
      host: longhorn.bytemagic.cloud
    persistence:
      defaultClassReplicaCount: 2
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9500"
      prometheus.io/path: "/metrics"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-retained
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  dataLocality: "disabled"
  fromBackup: ""
  fsType: "ext4"
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: "ignored"
